----CUTS---
--RCHG_DT = CURRENT DATE -60 AND CURRENT DATE -1
--RCHG_COUNT >= 3
--IN = 'Y'
--VLR = 'Y'
--DND = 'N'

DROP TABLE DB2PROJ.MA_99_RCHG_TEMP;

CREATE TABLE DB2PROJ.MA_99_RCHG_TEMP AS (
SELECT A.SUBS_CIRCLE_ID,A.SUBS_MSISDN
,CASE WHEN VLR.SUBS_MSISDN IS NOT NULL THEN 'Y' ELSE 'N' END AS VLR_TAG
,CASE WHEN DND.SUBS_MSISDN IS NOT NULL THEN 'Y' ELSE 'N' END AS DND_TAG
,CASE WHEN IN.SUBS_MSISDN IS NOT NULL THEN 'Y' END AS INBASE_TAG

 FROM(
SELECT SUBS_CIRCLE_ID,SUBS_MSISDN,COUNT(SUBS_MSISDN)CNT FROM FACT_DATALAKE.FCT_SUBS_RCHG_HISTORY 
WHERE SUBS_CIRCLE_ID IN (21,22) AND RCHG_MRP_AMT = 99 AND REPORTED_DATE BETWEEN CURRENT DATE -60 AND CURRENT DATE -1 
GROUP BY SUBS_CIRCLE_ID,SUBS_MSISDN) A



LEFT JOIN (SELECT DISTINCT SUBS_MSISDN FROM fact_DATALAKE.FCT_SUBS_VLR_HISTORY WHERE SUBS_CIRCLE_ID IN (21,22) AND VLR_START_DATE <= CURRENT DATE - 2 DAYS AND VLR_END_DATE >CURRENT DATE - 2 DAYS)VLR 
    ON A.SUBS_MSISDN = VLR.SUBS_MSISDN

LEFT JOIN (Select subs_msisdn from fact_datalake.FCT_SUBS_DLT_PREF_HISTORY WHERE dnd_prf_end_dt='9999-12-31' GROUP BY subs_msisdn)DND
    ON A.SUBS_MSISDN = DND.SUBS_MSISDN
    
LEFT JOIN (SELECT SUBS_MSISDN,BRAND_ID FROM DIM_DATALAKE.DIM_SUBS_MASTER WHERE DISCONNECTION_DATE >= (CURRENT DATE - 2) AND UNBAR_DATE <= (CURRENT DATE - 2)AND CIRCLE_ID IN (21,22) AND BRAND_ID IN ('1','2')) IN -- USE LATEST TABLE
	 ON A.SUBS_MSISDN = IN.SUBS_MSISDN 
	 
WHERE A.CNT >=3 )WITH NO DATA;

INSERT INTO DB2PROJ.MA_99_RCHG_TEMP (
SELECT A.SUBS_CIRCLE_ID,A.SUBS_MSISDN
,CASE WHEN VLR.SUBS_MSISDN IS NOT NULL THEN 'Y' ELSE 'N' END AS VLR_TAG
,CASE WHEN DND.SUBS_MSISDN IS NOT NULL THEN 'Y' ELSE 'N' END AS DND_TAG
,CASE WHEN IN.SUBS_MSISDN IS NOT NULL THEN 'Y' END AS INBASE_TAG

 FROM(
SELECT SUBS_CIRCLE_ID,SUBS_MSISDN,COUNT(SUBS_MSISDN)CNT FROM FACT_DATALAKE.FCT_SUBS_RCHG_HISTORY 
WHERE SUBS_CIRCLE_ID IN (21,22) AND RCHG_MRP_AMT = 99 AND REPORTED_DATE BETWEEN CURRENT DATE -60 AND CURRENT DATE -1 
GROUP BY SUBS_CIRCLE_ID,SUBS_MSISDN) A



LEFT JOIN (SELECT DISTINCT SUBS_MSISDN FROM fact_DATALAKE.FCT_SUBS_VLR_HISTORY WHERE SUBS_CIRCLE_ID IN (21,22) AND VLR_START_DATE <= CURRENT DATE - 2 DAYS AND VLR_END_DATE >CURRENT DATE - 2 DAYS)VLR 
    ON A.SUBS_MSISDN = VLR.SUBS_MSISDN

LEFT JOIN (Select subs_msisdn from fact_datalake.FCT_SUBS_DLT_PREF_HISTORY WHERE dnd_prf_end_dt='9999-12-31' GROUP BY subs_msisdn)DND
    ON A.SUBS_MSISDN = DND.SUBS_MSISDN
    
LEFT JOIN (SELECT SUBS_MSISDN,BRAND_ID FROM DIM_DATALAKE.DIM_SUBS_MASTER WHERE DISCONNECTION_DATE >= (CURRENT DATE - 2) AND UNBAR_DATE <= (CURRENT DATE - 2)AND CIRCLE_ID IN (21,22) AND BRAND_ID IN ('1','2')) IN -- USE LATEST TABLE
	 ON A.SUBS_MSISDN = IN.SUBS_MSISDN 
	 
WHERE A.CNT >=3 );


--SELECT SUBS_CIRCLE_ID,VLR_TAG, COUNT(SUBS_MSISDN) FROM DB2PROJ.MA_99_RCHG_TEMP WHERE  DND_TAG = 'N'AND INBASE_TAG = 'Y' GROUP BY SUBS_CIRCLE_ID,VLR_TAG ;

--UE
Export to C:\Shivam\SQL\99_Repeat_Taker\exported\UE_99_RCHG_VLR.txt of del modified by  NOCHARDEL coldel, striplzeros decplusblanK

SELECT DISTINCT SUBS_MSISDN FROM DB2PROJ.MA_99_RCHG_TEMP WHERE  DND_TAG = 'N'AND INBASE_TAG = 'Y' AND VLR_TAG = 'Y' AND SUBS_CIRCLE_ID = 21  ;

Export to C:\Shivam\SQL\99_Repeat_Taker\exported\UE_99_RCHG_NONVLR.txt of del modified by  NOCHARDEL coldel, striplzeros decplusblanK

SELECT DISTINCT SUBS_MSISDN FROM DB2PROJ.MA_99_RCHG_TEMP WHERE  DND_TAG = 'N'AND INBASE_TAG = 'Y' AND VLR_TAG = 'N' AND SUBS_CIRCLE_ID = 21  ;

--UW

Export to C:\Shivam\SQL\99_Repeat_Taker\exported\UW_99_RCHG_VLR.txt of del modified by  NOCHARDEL coldel, striplzeros decplusblanK

SELECT DISTINCT SUBS_MSISDN FROM DB2PROJ.MA_99_RCHG_TEMP WHERE  DND_TAG = 'N'AND INBASE_TAG = 'Y' AND VLR_TAG = 'Y' AND SUBS_CIRCLE_ID = 22  ;

Export to C:\Shivam\SQL\99_Repeat_Taker\exported\UW_99_RCHG_NONVLR.txt of del modified by  NOCHARDEL coldel, striplzeros decplusblanK

SELECT DISTINCT SUBS_MSISDN FROM DB2PROJ.MA_99_RCHG_TEMP WHERE  DND_TAG = 'N'AND INBASE_TAG = 'Y' AND VLR_TAG = 'N' AND SUBS_CIRCLE_ID = 22  ;
