SELECT MIN(create_date),MAX(create_date) FROM DB2PROJ.HS_MNP_TUP;
--MY TABLE
SELECT REPORTED_DATE,SUBS_CIRCLE_ID,COUNT(SUBS_MSISDN) FROM DB2PROJ.HS_FCT_SUBS_RCHG_HISTORY WHERE REPORTED_DATE >= CURRENT DATE - 4 GROUP BY REPORTED_DATE,SUBS_CIRCLE_ID ORDER BY REPORTED_DATE,SUBS_CIRCLE_ID;
SELECT REPORTED_DATE,SUBS_CIRCLE_ID,COUNT(SUBS_MSISDN) FROM DB2PROJ.HS_ONLINE_SENDER_ID_TUP WHERE REPORTED_DATE >= CURRENT DATE - 4 GROUP BY REPORTED_DATE,SUBS_CIRCLE_ID ORDER BY REPORTED_DATE,SUBS_CIRCLE_ID;
SELECT REPORTED_DATE,SUBS_CIRCLE_ID,COUNT(SUBS_MSISDN) FROM DB2PROJ.HS_FCT_PUSH_BASE_MSISDN_TUP WHERE REPORTED_DATE >= CURRENT DATE - 4 GROUP BY REPORTED_DATE,SUBS_CIRCLE_ID ORDER BY REPORTED_DATE,SUBS_CIRCLE_ID;
--SELECT SUBS_CIRCLE_ID,REPORTED_DATE,COUNT(SUBS_MSISDN) FROM DB2PROJ.HS_ONLINE_SENDER_ID_TUP GROUP BY SUBS_CIRCLE_ID,REPORTED_DATE ORDER BY REPORTED_DATE DESC limit 10;


--MOTHER TABLE
SELECT SUBS_CIRCLE_ID,COUNT(SUBS_MSISDN) FROM FACT_DATALAKE.FCT_SUBS_RCHG_HISTORY WHERE REPORTED_DATE = CURRENT DATE - 1 GROUP BY SUBS_CIRCLE_ID;
SELECT MIN(reported_date),MAX(reported_date) FROM DIM_DATALAKE.DIM_SUBS_RCHG_DFRMNT_BASE;
SELECT SUBS_CIRCLE_ID,COUNT(SUBS_MSISDN) FROM AGGR_DATALAKE.AGG_SUBS_USAGE_MSC_DAILY_22 WHERE REPORTED_DATE = CURRENT DATE - 1 GROUP BY SUBS_CIRCLE_ID;
SELECT SUBS_CIRCLE_ID,COUNT(SUBS_MSISDN) FROM AGGR_DATALAKE.AGG_SUBS_USAGE_MSC_DAILY_21 WHERE REPORTED_DATE = CURRENT DATE - 1 GROUP BY SUBS_CIRCLE_ID;


----INSERT YAHAN SE HOGI---------
--RECHARGE TABLE DB2PROJ.HS_FCT_SUBS_RCHG_HISTORY
INSERT INTO DB2PROJ.HS_FCT_SUBS_RCHG_HISTORY(
SELECT SUBS_MSISDN,RCHG_DT,RCHG_TIME,REPORTED_DATE,(REPORTED_DATE+CAST(RCHG_VALIDITY_IN_DAYS AS INT))-1 AS OFFER_EXPIRY_DATE,
RCHG_MRP_AMT,SUBS_CIRCLE_ID,RCHG_CIRCLE_ID,CHNL_RTLR_ID,RCHG_VALIDITY_IN_DAYS,TRF_PLAN_KEY,RCHG_CATEGORY_ID,REC_TYPE,RCHG_TYPE_KEY,ORIGIN_TRANSACTION_ID,
ORIGIN_OPERATOR_ID,PARTNER_REF_ID,ACTIVATION_DATE,
case 
when upper(CHNL_RTLR_ID) like '%AMAZON%'then 'Amazon Pay' when upper(CHNL_RTLR_ID) like '%AZPAY%' then 'Amazon Pay'
when upper(CHNL_RTLR_ID) like '%GTEZ%'  then 'Google Tez' when upper(CHNL_RTLR_ID) like '%GPAY%'  then 'Google Tez'
when upper(CHNL_RTLR_ID) like '%PAYTM%' then 'Paytm' when upper(CHNL_RTLR_ID) like '%PAYTM%' then 'Paytm'
when upper(CHNL_RTLR_ID) like '%PHNP%'  then 'PhonePe' when upper(CHNL_RTLR_ID) like '%PHNP%'  then 'PhonePe'
when upper(CHNL_RTLR_ID) like '%MIA%'   then 'Vi App'  when upper(CHNL_RTLR_ID) like '%MVA%'   then 'Vi App' 
when upper(CHNL_RTLR_ID) like '%MOBIKWIK%' then 'Mobikwik' else 
(case  when upper(PARTNER_REF_ID) like '%MOBIKWIK%' then 'Mobikwik' when upper(PARTNER_REF_ID) like '%PHNP%'   then 'PhonePe' when upper(PARTNER_REF_ID) like '%GPAY%'  then 'Google Tez' 
when upper(PARTNER_REF_ID) like '%AZPAY%' then 'Amazon Pay'  ELSE 'OTHERS' END)END AS DIGITAL_TAG
FROM FACT_DATALAKE.FCT_SUBS_RCHG_HISTORY
WHERE SUBS_CIRCLE_ID IN (21,22)
--AND REPORTED_DATE = '2023-05-09');
AND REPORTED_DATE BETWEEN '2023-11-08' AND '2023-11-08');---- current date - 1



--ONLINE SENDER ID TABLE DB2PROJ.HS_ONLINE_SENDER_ID_TUP
INSERT INTO DB2PROJ.HS_ONLINE_SENDER_ID_TUP
(Select SUBS_MSISDN,SUBS_CIRCLE_ID,BRAND,CALLED_CALLING_NUMBER,REPORTED_DATE,
CASE WHEN UPPER(CALLED_CALLING_NUMBER) = '575754' OR UPPER(CALLED_CALLING_NUMBER) = '57575022' OR UPPER(CALLED_CALLING_NUMBER) = '57575701' OR UPPER(CALLED_CALLING_NUMBER) = '50270000' THEN 'AMAZONPAY' 
WHEN UPPER(CALLED_CALLING_NUMBER) LIKE '%FCHARG%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%FCHRGE%' THEN 'FREECHARGE'
WHEN UPPER(CALLED_CALLING_NUMBER) LIKE '%PHONPE%' THEN 'PHONEPE'
WHEN UPPER(CALLED_CALLING_NUMBER) LIKE '%HOTSTR%' THEN 'HOTSTAR'
WHEN UPPER(CALLED_CALLING_NUMBER) LIKE '%EGPAYM%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%GPAYQR%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%MRGPAY%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%MYGPAY%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%SMGPAY%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%CHGPAY%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%GPAYEX%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%TMGPAY%' THEN 'GPAY'
WHEN UPPER(CALLED_CALLING_NUMBER) LIKE '%IPAYTM%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%PAYTMB%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%PAYTMI%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%PAYTMM%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%VPAYTM%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%PAYTMC%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%PAYTMH%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%PAYTMD%' THEN 'PAYTM'
END AS SENDER_ID
from  AGGR_DATALAKE.AGG_SUBS_USAGE_MSC_DAILY_21
WHERE SUBS_CIRCLE_ID IN (21,22) AND REPORTED_DATE BETWEEN '2023-11-08' AND '2023-11-08'
AND (UPPER(CALLED_CALLING_NUMBER) = '575754' OR UPPER(CALLED_CALLING_NUMBER) = '57575022' OR UPPER(CALLED_CALLING_NUMBER) = '57575701' OR UPPER(CALLED_CALLING_NUMBER) = '50270000'
OR UPPER(CALLED_CALLING_NUMBER) LIKE '%FCHARG%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%FCHRGE%'
OR UPPER(CALLED_CALLING_NUMBER) LIKE '%PHONPE%'
OR UPPER(CALLED_CALLING_NUMBER) LIKE '%HOTSTR%'
OR UPPER(CALLED_CALLING_NUMBER) LIKE '%EGPAYM%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%GPAYQR%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%MRGPAY%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%MYGPAY%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%SMGPAY%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%CHGPAY%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%GPAYEX%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%TMGPAY%'
OR UPPER(CALLED_CALLING_NUMBER) LIKE '%IPAYTM%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%PAYTMB%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%PAYTMI%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%PAYTMM%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%VPAYTM%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%PAYTMC%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%PAYTMH%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%PAYTMD%'
));


INSERT INTO DB2PROJ.HS_ONLINE_SENDER_ID_TUP
(Select SUBS_MSISDN,SUBS_CIRCLE_ID,BRAND,CALLED_CALLING_NUMBER,REPORTED_DATE,
CASE WHEN UPPER(CALLED_CALLING_NUMBER) = '575754' OR UPPER(CALLED_CALLING_NUMBER) = '57575022' OR UPPER(CALLED_CALLING_NUMBER) = '57575701' OR UPPER(CALLED_CALLING_NUMBER) = '50270000' THEN 'AMAZONPAY' 
WHEN UPPER(CALLED_CALLING_NUMBER) LIKE '%FCHARG%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%FCHRGE%' THEN 'FREECHARGE'
WHEN UPPER(CALLED_CALLING_NUMBER) LIKE '%PHONPE%' THEN 'PHONEPE'
WHEN UPPER(CALLED_CALLING_NUMBER) LIKE '%HOTSTR%' THEN 'HOTSTAR'
WHEN UPPER(CALLED_CALLING_NUMBER) LIKE '%EGPAYM%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%GPAYQR%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%MRGPAY%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%MYGPAY%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%SMGPAY%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%CHGPAY%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%GPAYEX%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%TMGPAY%' THEN 'GPAY'
WHEN UPPER(CALLED_CALLING_NUMBER) LIKE '%IPAYTM%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%PAYTMB%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%PAYTMI%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%PAYTMM%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%VPAYTM%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%PAYTMC%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%PAYTMH%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%PAYTMD%' THEN 'PAYTM'
END AS SENDER_ID
from  AGGR_DATALAKE.AGG_SUBS_USAGE_MSC_DAILY_22
WHERE SUBS_CIRCLE_ID IN (21,22) AND REPORTED_DATE BETWEEN '2023-11-08' AND '2023-11-08'
AND (UPPER(CALLED_CALLING_NUMBER) = '575754' OR UPPER(CALLED_CALLING_NUMBER) = '57575022' OR UPPER(CALLED_CALLING_NUMBER) = '57575701' OR UPPER(CALLED_CALLING_NUMBER) = '50270000'
OR UPPER(CALLED_CALLING_NUMBER) LIKE '%FCHARG%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%FCHRGE%'
OR UPPER(CALLED_CALLING_NUMBER) LIKE '%PHONPE%'
OR UPPER(CALLED_CALLING_NUMBER) LIKE '%HOTSTR%'
OR UPPER(CALLED_CALLING_NUMBER) LIKE '%EGPAYM%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%GPAYQR%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%MRGPAY%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%MYGPAY%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%SMGPAY%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%CHGPAY%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%GPAYEX%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%TMGPAY%'
OR UPPER(CALLED_CALLING_NUMBER) LIKE '%IPAYTM%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%PAYTMB%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%PAYTMI%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%PAYTMM%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%VPAYTM%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%PAYTMC%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%PAYTMH%' OR UPPER(CALLED_CALLING_NUMBER) LIKE '%PAYTMD%'
));	


--DATA BREACHER (DATA BURSTER TABLE)     ---- 10 OCT NOT Updated             
INSERT INTO DB2PROJ.HS_FCT_PUSH_BASE_MSISDN_TUP
(SELECT MSISDN AS SUBS_MSISDN,BI_CIRCLE_ID as subs_circle_id,reported_date
FROM  FACT_DATALAKE.FCT_PUSH_BASE_MSISDN 
WHERE REPORTED_DATE BETWEEN '2023-11-08' AND '2023-11-08' AND BI_CIRCLE_ID IN (21,22) 
AND CAMPAIGN_NAME IN ('NAT_DATABURST_NULACTIVE_NONDATA_VI','NAT_DATABURST_NULACTIVE_VI','NAT_DATABURST_ULACTIVE_NONDATA_VI','NAT_DATABURST_ULACTIVE_VI','NAT_DATABURST_ULEXPIRY_NONDATA_VI','NAT_DATABURST_ULEXPIRY_VI')); 




---------------------%%%%%%%%%%%%%%%%%%-------------------------------

--Data Burster table CHK
SELECT MAX(REPORTED_DATE) FROM   FACT_DATALAKE.FCT_PUSH_BASE_MSISDN WHERE BI_CIRCLE_ID IN (21,22) LIMIT 10