
DROP TABLE DB2PROJ.HARI_DATA_BURSTER_TEMP;

CREATE TABLE DB2PROJ.HARI_DATA_BURSTER_TEMP AS (
SELECT A.SUBS_MSISDN,A.SUBS_CIRCLE_ID,A.OFFER_NAME,B.REVENUE_END_DT,B.RCHG_MRP_AMT,C.DP_MRP_AMT,
 CASE WHEN c.subs_msisdn IS NOT NULL THEN 'Y' ELSE 'N' END AS DP_TAKER
,CASE WHEN VLR.SUBS_MSISDN IS NOT NULL THEN 'Y' ELSE 'N' END AS VLR_TAG
,CASE WHEN DND.SUBS_MSISDN IS NOT NULL THEN 'Y' ELSE 'N' END AS DND_TAG
 
  FROM 
(SELECT MSISDN AS SUBS_MSISDN,BI_CIRCLE_ID AS SUBS_CIRCLE_ID ,OFFER_NAME FROM  FACT_DATALAKE.FCT_PUSH_BASE_MSISDN 
WHERE REPORTED_DATE = (CURRENT DATE - 1) AND BI_CIRCLE_ID IN (21,22)
AND OFFER_NAME IN ('DATABURST_NUL_SV_NAT','DATABURST_Nondatataker_NAT_1','DATABURST_ULACTIVE_NAT_ULV28D','DATABURST_ULACTIVE_NAT_ULV_LV','DATABURST_ULACTIVE_NAT_ULD_SET1','DATABURST_ULACTIVE_NAT_ULD_SET2','DATABURST_ULACTIVE_DPTAKER_NAT'))A

LEFT JOIN
(SELECT SUBS_MSISDN,REVENUE_END_DT,SUBS_CIRCLE_ID,RCHG_MRP_AMT FROM
(SELECT SUBS_MSISDN,REVENUE_END_DT,SUBS_CIRCLE_ID,RCHG_MRP_AMT,ROW_NUMBER() OVER (PARTITION BY SUBS_MSISDN ORDER BY SUBS_MSISDN,REVENUE_END_DT desc)RN 
FROM DIM_DATALAKE.DIM_SUBS_RCHG_DFRMNT_BASE
WHERE SUBS_CIRCLE_ID IN (21,22) AND RCHG_CATEGORY IN (11,16) AND RCHG_MRP_AMT > 0 )
WHERE RN = 1) B
ON A.SUBS_MSISDN = B.SUBS_MSISDN

LEFT JOIN (SELECT SUBS_MSISDN,MAX(RCHG_MRP_AMT)DP_MRP_AMT FROM FACT_DATALAKE.FCT_SUBS_RCHG_HISTORY WHERE SUBS_CIRCLE_ID IN (21,22)  AND RCHG_CATEGORY_ID = '2' AND RCHG_MRP_AMT > 0 AND REPORTED_DATE BETWEEN CURRENT DATE - 16 AND CURRENT DATE - 1 GROUP BY SUBS_MSISDN)C  
	ON A.SUBS_MSISDN = C.SUBS_MSISDN

LEFT JOIN
 (SELECT DISTINCT SUBS_MSISDN FROM fact_DATALAKE.FCT_SUBS_VLR_HISTORY WHERE SUBS_CIRCLE_ID IN (21,22) AND VLR_START_DATE <= CURRENT DATE - 2 DAYS AND VLR_END_DATE >CURRENT DATE - 2 DAYS)VLR
 ON A.SUBS_MSISDN = VLR.SUBS_MSISDN

LEFT JOIN (Select subs_msisdn from fact_datalake.FCT_SUBS_DLT_PREF_HISTORY WHERE dnd_prf_end_dt='9999-12-31' GROUP BY subs_msisdn)DND
ON A.SUBS_MSISDN = DND.SUBS_MSISDN

INNER JOIN (SELECT SUBS_MSISDN,BRAND_ID FROM DIM_DATALAKE.DIM_SUBS_MASTER WHERE DISCONNECTION_DATE >= (CURRENT DATE - 2) AND UNBAR_DATE <= (CURRENT DATE - 2)AND CIRCLE_ID IN (21,22) AND BRAND_ID IN ('1','2') GROUP BY SUBS_MSISDN,BRAND_ID) IN -- USE LATEST TABLE
  ON A.SUBS_MSISDN = IN.SUBS_MSISDN  ) WITH NO DATA;

INSERT INTO DB2PROJ.HARI_DATA_BURSTER_TEMP (
SELECT A.SUBS_MSISDN,A.SUBS_CIRCLE_ID,A.OFFER_NAME,B.REVENUE_END_DT,B.RCHG_MRP_AMT,C.DP_MRP_AMT,
 CASE WHEN c.subs_msisdn IS NOT NULL THEN 'Y' ELSE 'N' END AS DP_TAKER
,CASE WHEN VLR.SUBS_MSISDN IS NOT NULL THEN 'Y' ELSE 'N' END AS VLR_TAG
,CASE WHEN DND.SUBS_MSISDN IS NOT NULL THEN 'Y' ELSE 'N' END AS DND_TAG
 
  FROM 
(SELECT MSISDN AS SUBS_MSISDN,BI_CIRCLE_ID AS SUBS_CIRCLE_ID ,OFFER_NAME FROM  FACT_DATALAKE.FCT_PUSH_BASE_MSISDN 
WHERE REPORTED_DATE = (CURRENT DATE - 1) AND BI_CIRCLE_ID IN (21,22)
AND OFFER_NAME IN ('DATABURST_NUL_SV_NAT','DATABURST_Nondatataker_NAT_1','DATABURST_ULACTIVE_NAT_ULV28D','DATABURST_ULACTIVE_NAT_ULV_LV','DATABURST_ULACTIVE_NAT_ULD_SET1','DATABURST_ULACTIVE_NAT_ULD_SET2','DATABURST_ULACTIVE_DPTAKER_NAT'))A

LEFT JOIN
(SELECT SUBS_MSISDN,REVENUE_END_DT,SUBS_CIRCLE_ID,RCHG_MRP_AMT FROM
(SELECT SUBS_MSISDN,REVENUE_END_DT,SUBS_CIRCLE_ID,RCHG_MRP_AMT,ROW_NUMBER() OVER (PARTITION BY SUBS_MSISDN ORDER BY SUBS_MSISDN,REVENUE_END_DT desc)RN 
FROM DIM_DATALAKE.DIM_SUBS_RCHG_DFRMNT_BASE
WHERE SUBS_CIRCLE_ID IN (21,22) AND RCHG_CATEGORY IN (11,16) AND RCHG_MRP_AMT > 0 )
WHERE RN = 1) B
ON A.SUBS_MSISDN = B.SUBS_MSISDN

LEFT JOIN (SELECT SUBS_MSISDN,MAX(RCHG_MRP_AMT)DP_MRP_AMT FROM FACT_DATALAKE.FCT_SUBS_RCHG_HISTORY WHERE SUBS_CIRCLE_ID IN (21,22)  AND RCHG_CATEGORY_ID = '2' AND RCHG_MRP_AMT > 0 AND REPORTED_DATE BETWEEN CURRENT DATE - 16 AND CURRENT DATE - 1 GROUP BY SUBS_MSISDN)C  
	ON A.SUBS_MSISDN = C.SUBS_MSISDN

LEFT JOIN
 (SELECT DISTINCT SUBS_MSISDN FROM fact_DATALAKE.FCT_SUBS_VLR_HISTORY 
WHERE SUBS_CIRCLE_ID IN (21,22) AND VLR_START_DATE <= CURRENT DATE - 2 DAYS AND VLR_END_DATE >CURRENT DATE - 2 DAYS)VLR 
ON A.SUBS_MSISDN = VLR.SUBS_MSISDN

LEFT JOIN (Select subs_msisdn from fact_datalake.FCT_SUBS_DLT_PREF_HISTORY 
WHERE dnd_prf_end_dt='9999-12-31' GROUP BY subs_msisdn)DND
ON A.SUBS_MSISDN = DND.SUBS_MSISDN

INNER JOIN (SELECT SUBS_MSISDN,BRAND_ID FROM DIM_DATALAKE.DIM_SUBS_MASTER WHERE DISCONNECTION_DATE >= (CURRENT DATE - 2) AND UNBAR_DATE <= (CURRENT DATE - 2)AND CIRCLE_ID IN (21,22) AND BRAND_ID IN ('1','2') GROUP BY SUBS_MSISDN,BRAND_ID) IN -- USE LATEST TABLE
  ON A.SUBS_MSISDN = IN.SUBS_MSISDN );