
--1499,1449,1799,2399,2595,2899,3099 rchg on dec and jan , currently not active
--479,539,599,666,719,839,1066 ,offer expiry (current Month to Current date + 15)

DROP TABLE DB2PROJ.HS_LV_BASE_1;
CREATE TABLE DB2PROJ.HS_LV_BASE_1 AS
(select A.SUBS_MSISDN,A.SUBS_CIRCLE_ID,IN.BRAND_ID,A.REPORTED_DATE,A.REVENUE_START_DT AS OFFER_START_DATE,A.REVENUE_END_DT AS OFFER_EXPIRY_DATE,A.RCHG_MRP_AMT AS UL_MRP,UL_CATEGORY
,DAYS(REVENUE_END_DT)-DAYS(REVENUE_START_DT)+1 AS VALIDIT,RCHG_SRC_IDENTIFIER AS RETAILER,CASE WHEN LEFT(RCHG_SRC_IDENTIFIER,1) IN ('6','7','8','9') THEN 'E' ELSE 'O' END MODE,
CASE WHEN HS.DEVICE_TYPE = '4G' THEN '4G' WHEN HS.DEVICE_TYPE = '5G' THEN '4G' ELSE 'NON4G' END AS DEVICE_TYPE,
CASE WHEN VLR.SUBS_MSISDN IS NOT NULL THEN 'Y' ELSE 'N' END AS VLR_TAG,
CASE WHEN DND.SUBS_MSISDN IS NOT NULL THEN 'Y' ELSE 'N' END AS DND_TAG,
CASE WHEN RC.SUBS_MSISDN IS NOT NULL THEN 'Y' END AS RECH_TAG,
CASE WHEN IN.SUBS_MSISDN IS NOT NULL THEN 'Y' END AS INBASE_TAG,
CASE WHEN AR.SUBS_MSISDN IS NOT NULL THEN 'Y' ELSE 'N' END AS ALRCHG_TAG
from DIM_DATALAKE.DIM_SUBS_RCHG_DFRMNT_BASE A
LEFT JOIN (SELECT RIGHT(subs_msisdn,10) AS subs_msisdn,DEVICE_TYPE FROM  DB2PROJ.HANDSET_MTD_TUP) HS 
	 ON A.SUBS_MSISDN = HS.SUBS_MSISDN
LEFT JOIN (SELECT DISTINCT SUBS_MSISDN FROM fact_DATALAKE.FCT_SUBS_VLR_HISTORY WHERE SUBS_CIRCLE_ID IN (21,22) AND VLR_START_DATE <= CURRENT DATE - 2 DAYS AND VLR_END_DATE >CURRENT DATE - 2 DAYS)VLR 
     ON A.SUBS_MSISDN = VLR.SUBS_MSISDN
LEFT JOIN (Select subs_msisdn from fact_datalake.FCT_SUBS_DLT_PREF_HISTORY WHERE dnd_prf_end_dt='9999-12-31' GROUP BY subs_msisdn)DND
     ON A.SUBS_MSISDN = DND.SUBS_MSISDN
LEFT JOIN (SELECT SUBS_MSISDN FROM FACT_DATALAKE.FCT_SUBS_RCHG_HISTORY WHERE SUBS_CIRCLE_ID IN (21,22) AND RCHG_TYPE_KEY IN (1,2) AND reported_date>=CURRENT DATE-14 DAYS GROUP BY SUBS_MSISDN) RC
   	 ON A.SUBS_MSISDN = RC.SUBS_MSISDN
LEFT JOIN (SELECT SUBS_MSISDN,BRAND_ID FROM DIM_DATALAKE.DIM_SUBS_MASTER WHERE DISCONNECTION_DATE >= (CURRENT DATE - 2) AND UNBAR_DATE <= (CURRENT DATE - 2)AND CIRCLE_ID IN (21,22) AND BRAND_ID IN ('1','2')) IN -- USE LATEST TABLE
	 ON A.SUBS_MSISDN = IN.SUBS_MSISDN
LEFT JOIN (SELECT SUBS_MSISDN FROM DIM_DATALAKE.DIM_SUBS_RCHG_DFRMNT_BASE WHERE SUBS_CIRCLE_ID IN (21,22) AND RCHG_CATEGORY = 16 AND REVENUE_END_DT > CURRENT DATE and rchg_mrp_amt >= 99 group by SUBS_MSISDN) AR
	 ON A.SUBS_MSISDN = AR.SUBS_MSISDN	
WHERE A.REVENUE_END_DT BETWEEN '2024-01-01' AND (CURRENT DATE +15)
 AND A.RCHG_MRP_AMT IN (1499,1449,1799,2399,2595,2899,3099)
 AND A.SUBS_CIRCLE_ID IN ('21','22')
 )WITH NO DATA;

INSERT INTO DB2PROJ.HS_LV_BASE_1 
(select A.SUBS_MSISDN,A.SUBS_CIRCLE_ID,IN.BRAND_ID,A.REPORTED_DATE,A.REVENUE_START_DT AS OFFER_START_DATE,A.REVENUE_END_DT AS OFFER_EXPIRY_DATE,A.RCHG_MRP_AMT AS UL_MRP,UL_CATEGORY
,DAYS(REVENUE_END_DT)-DAYS(REVENUE_START_DT)+1 AS VALIDIT,RCHG_SRC_IDENTIFIER AS RETAILER,CASE WHEN LEFT(RCHG_SRC_IDENTIFIER,1) IN ('6','7','8','9') THEN 'E' ELSE 'O' END MODE,
CASE WHEN HS.DEVICE_TYPE = '4G' THEN '4G' WHEN HS.DEVICE_TYPE = '5G' THEN '4G' ELSE 'NON4G' END AS DEVICE_TYPE,
CASE WHEN VLR.SUBS_MSISDN IS NOT NULL THEN 'Y' ELSE 'N' END AS VLR_TAG,
CASE WHEN DND.SUBS_MSISDN IS NOT NULL THEN 'Y' ELSE 'N' END AS DND_TAG,
CASE WHEN RC.SUBS_MSISDN IS NOT NULL THEN 'Y' END AS RECH_TAG,
CASE WHEN IN.SUBS_MSISDN IS NOT NULL THEN 'Y' END AS INBASE_TAG,
CASE WHEN AR.SUBS_MSISDN IS NOT NULL THEN 'Y' ELSE 'N' END AS ALRCHG_TAG
from DIM_DATALAKE.DIM_SUBS_RCHG_DFRMNT_BASE A
LEFT JOIN (SELECT RIGHT(subs_msisdn,10) AS subs_msisdn,DEVICE_TYPE FROM  DB2PROJ.HANDSET_MTD_TUP) HS 
	 ON A.SUBS_MSISDN = HS.SUBS_MSISDN
LEFT JOIN (SELECT DISTINCT SUBS_MSISDN FROM fact_DATALAKE.FCT_SUBS_VLR_HISTORY WHERE SUBS_CIRCLE_ID IN (21,22) AND VLR_START_DATE <= CURRENT DATE - 2 DAYS AND VLR_END_DATE >CURRENT DATE - 2 DAYS)VLR 
     ON A.SUBS_MSISDN = VLR.SUBS_MSISDN
LEFT JOIN (Select subs_msisdn from fact_datalake.FCT_SUBS_DLT_PREF_HISTORY WHERE dnd_prf_end_dt='9999-12-31' GROUP BY subs_msisdn)DND
     ON A.SUBS_MSISDN = DND.SUBS_MSISDN
LEFT JOIN (SELECT SUBS_MSISDN FROM FACT_DATALAKE.FCT_SUBS_RCHG_HISTORY WHERE SUBS_CIRCLE_ID IN (21,22) AND RCHG_TYPE_KEY IN (1,2) AND reported_date>=CURRENT DATE-14 DAYS GROUP BY SUBS_MSISDN) RC
   	 ON A.SUBS_MSISDN = RC.SUBS_MSISDN
LEFT JOIN (SELECT SUBS_MSISDN,BRAND_ID FROM DIM_DATALAKE.DIM_SUBS_MASTER WHERE DISCONNECTION_DATE >= (CURRENT DATE - 2) AND UNBAR_DATE <= (CURRENT DATE - 2)AND CIRCLE_ID IN (21,22) AND BRAND_ID IN ('1','2')) IN -- USE LATEST TABLE
	 ON A.SUBS_MSISDN = IN.SUBS_MSISDN
LEFT JOIN (SELECT SUBS_MSISDN FROM DIM_DATALAKE.DIM_SUBS_RCHG_DFRMNT_BASE WHERE SUBS_CIRCLE_ID IN (21,22) AND RCHG_CATEGORY = 16 AND REVENUE_END_DT > CURRENT DATE and rchg_mrp_amt >= 99 group by SUBS_MSISDN) AR
	 ON A.SUBS_MSISDN = AR.SUBS_MSISDN
LEFT JOIN (SELECT SUBS_MSISDN FROM DB2PROJ.UCG_BASE)UCG ON UCG.SUBS_MSISDN = A.SUBS_MSISDN	
WHERE A.REVENUE_END_DT BETWEEN '2024-01-01' AND (CURRENT DATE +15)
 AND A.RCHG_MRP_AMT IN (1499,1449,1799,2399,2595,2899,3099)
 AND A.SUBS_CIRCLE_ID IN ('21','22') AND UCG.SUBS_MSISDN IS NULL
 );

grant select on DB2PROJ.HS_LV_BASE_1 to public;

------------------------------------------------------------------ HS_UL_BASE_2_3 ------------------------------------------------------------------

DROP TABLE DB2PROJ.HS_UL_BASE_2_3;

CREATE TABLE DB2PROJ.HS_UL_BASE_2_3 AS
(select A.*,IN.BRAND_ID,
CASE WHEN HS.DEVICE_TYPE = '4G' THEN '4G' WHEN HS.DEVICE_TYPE = '5G' THEN '4G' ELSE 'NON4G' END AS DEVICE_TYPE,
CASE WHEN VLR.SUBS_MSISDN IS NOT NULL THEN 'Y' ELSE 'N' END AS VLR_TAG,
CASE WHEN DND.SUBS_MSISDN IS NOT NULL THEN 'Y' ELSE 'N' END AS DND_TAG,
CASE WHEN RC.SUBS_MSISDN IS NOT NULL THEN 'Y' END AS RECH_TAG,
CASE WHEN IN.SUBS_MSISDN IS NOT NULL THEN 'Y' END AS INBASE_TAG
from (SELECT * FROM
(SELECT SUBS_MSISDN,SUBS_CIRCLE_ID,RCHG_CATEGORY,REPORTED_DATE,REVENUE_START_DT,REVENUE_END_DT,cast(RCHG_MRP_AMT AS int) AS RCHG_MRP_AMT,RCHG_VALIDITY_IN_DAYS,RCHG_SRC_IDENTIFIER,CASE WHEN LEFT(RCHG_SRC_IDENTIFIER,1) IN ('6','7','8','9') THEN 'E' ELSE 'O' END MODE,ROW_NUMBER() OVER (PARTITION BY SUBS_MSISDN ORDER BY SUBS_MSISDN,REVENUE_END_DT desc)RN FROM DIM_DATALAKE.DIM_SUBS_RCHG_DFRMNT_BASE
WHERE SUBS_CIRCLE_ID IN (21,22) AND RCHG_CATEGORY IN (11,16) AND RCHG_MRP_AMT >0 AND REVENUE_END_DT >= '2023-12-01') 
WHERE RN = 1 AND REVENUE_END_DT BETWEEN (CURRENT DATE -6) AND (CURRENT DATE +15)
AND RCHG_MRP_AMT IN (319,368,369,479,539,599,666,699,719,839,901,1066,195,289,296,329,429,459,537,949,2999))a
LEFT JOIN (SELECT subs_msisdn,DEVICE_TYPE FROM  DB2PROJ.HANDSET_MTD_TUP GROUP BY subs_msisdn,DEVICE_TYPE) HS 
	 ON A.SUBS_MSISDN = HS.SUBS_MSISDN
LEFT JOIN (SELECT SUBS_MSISDN FROM fact_DATALAKE.FCT_SUBS_VLR_HISTORY WHERE SUBS_CIRCLE_ID IN (21,22) AND VLR_START_DATE <= CURRENT DATE - 2 DAYS AND VLR_END_DATE >CURRENT DATE - 2 DAYS GROUP BY SUBS_MSISDN)VLR 
     ON A.SUBS_MSISDN = VLR.SUBS_MSISDN
LEFT JOIN (Select subs_msisdn from fact_datalake.FCT_SUBS_DLT_PREF_HISTORY WHERE dnd_prf_end_dt='9999-12-31' GROUP BY subs_msisdn)DND
     ON A.SUBS_MSISDN = DND.SUBS_MSISDN
LEFT JOIN (SELECT SUBS_MSISDN FROM fact_datalake.FCT_SUBS_RCHG_HISTORY WHERE SUBS_CIRCLE_ID IN (21,22) AND RCHG_CATEGORY_ID IN (11,16) AND reported_date>=CURRENT DATE-14 DAYS GROUP BY SUBS_MSISDN) RC
   	 ON A.SUBS_MSISDN = RC.SUBS_MSISDN
LEFT JOIN (SELECT SUBS_MSISDN,BRAND_ID FROM DIM_DATALAKE.DIM_SUBS_MASTER WHERE DISCONNECTION_DATE >= (CURRENT DATE - 2) AND UNBAR_DATE <= (CURRENT DATE - 2)AND CIRCLE_ID IN (21,22) AND BRAND_ID IN ('1','2') GROUP BY SUBS_MSISDN,BRAND_ID) IN -- USE LATEST TABLE
	 ON A.SUBS_MSISDN = IN.SUBS_MSISDN)WITH NO DATA;

INSERT INTO DB2PROJ.HS_UL_BASE_2_3 
(select A.*,IN.BRAND_ID,
CASE WHEN HS.DEVICE_TYPE = '4G' THEN '4G' WHEN HS.DEVICE_TYPE = '5G' THEN '4G' ELSE 'NON4G' END AS DEVICE_TYPE,
CASE WHEN VLR.SUBS_MSISDN IS NOT NULL THEN 'Y' ELSE 'N' END AS VLR_TAG,
CASE WHEN DND.SUBS_MSISDN IS NOT NULL THEN 'Y' ELSE 'N' END AS DND_TAG,
CASE WHEN RC.SUBS_MSISDN IS NOT NULL THEN 'Y' END AS RECH_TAG,
CASE WHEN IN.SUBS_MSISDN IS NOT NULL THEN 'Y' END AS INBASE_TAG
from (SELECT * FROM
(SELECT SUBS_MSISDN,SUBS_CIRCLE_ID,RCHG_CATEGORY,REPORTED_DATE,REVENUE_START_DT,REVENUE_END_DT,cast(RCHG_MRP_AMT AS int) AS RCHG_MRP_AMT,RCHG_VALIDITY_IN_DAYS,RCHG_SRC_IDENTIFIER,CASE WHEN LEFT(RCHG_SRC_IDENTIFIER,1) IN ('6','7','8','9') THEN 'E' ELSE 'O' END MODE,ROW_NUMBER() OVER (PARTITION BY SUBS_MSISDN ORDER BY SUBS_MSISDN,REVENUE_END_DT desc)RN FROM DIM_DATALAKE.DIM_SUBS_RCHG_DFRMNT_BASE
WHERE SUBS_CIRCLE_ID IN (21,22) AND RCHG_CATEGORY IN (11,16) AND RCHG_MRP_AMT >0 AND REVENUE_END_DT >= '2023-12-01') 
WHERE RN = 1 AND REVENUE_END_DT BETWEEN (CURRENT DATE -6) AND (CURRENT DATE +15)
AND RCHG_MRP_AMT IN (319,368,369,479,539,599,666,699,719,839,901,1066,195,289,296,329,429,459,537,949,2999))a
LEFT JOIN (SELECT subs_msisdn,DEVICE_TYPE FROM  DB2PROJ.HANDSET_MTD_TUP GROUP BY subs_msisdn,DEVICE_TYPE) HS 
	 ON A.SUBS_MSISDN = HS.SUBS_MSISDN
LEFT JOIN (SELECT SUBS_MSISDN FROM fact_DATALAKE.FCT_SUBS_VLR_HISTORY WHERE SUBS_CIRCLE_ID IN (21,22) AND VLR_START_DATE <= CURRENT DATE - 2 DAYS AND VLR_END_DATE >CURRENT DATE - 2 DAYS GROUP BY SUBS_MSISDN)VLR 
     ON A.SUBS_MSISDN = VLR.SUBS_MSISDN
LEFT JOIN (Select subs_msisdn from fact_datalake.FCT_SUBS_DLT_PREF_HISTORY WHERE dnd_prf_end_dt='9999-12-31' GROUP BY subs_msisdn)DND
     ON A.SUBS_MSISDN = DND.SUBS_MSISDN
LEFT JOIN (SELECT SUBS_MSISDN FROM fact_datalake.FCT_SUBS_RCHG_HISTORY WHERE SUBS_CIRCLE_ID IN (21,22) AND RCHG_CATEGORY_ID IN (11,16) AND reported_date>=CURRENT DATE-14 DAYS GROUP BY SUBS_MSISDN) RC
   	 ON A.SUBS_MSISDN = RC.SUBS_MSISDN
LEFT JOIN (SELECT SUBS_MSISDN,BRAND_ID FROM DIM_DATALAKE.DIM_SUBS_MASTER WHERE DISCONNECTION_DATE >= (CURRENT DATE - 2) AND UNBAR_DATE <= (CURRENT DATE - 2)AND CIRCLE_ID IN (21,22) AND BRAND_ID IN ('1','2') GROUP BY SUBS_MSISDN,BRAND_ID) IN -- USE LATEST TABLE
	 ON A.SUBS_MSISDN = IN.SUBS_MSISDN
LEFT JOIN (SELECT SUBS_MSISDN FROM DB2PROJ.UCG_BASE)UCG ON UCG.SUBS_MSISDN = A.SUBS_MSISDN WHERE UCG.SUBS_MSISDN IS NULL);
	 
grant select on DB2PROJ.HS_UL_BASE_2_3 to public;