
--SELECT COUNT (*) FROM DB2PROJ.MA_RCUU_NONRC_PCN_TEMP WHERE RCUU_TAG = 'N' AND VLR_TAG = 'Y' AND DND_TAG = 'N';
--SELECT COUNT (*) FROM DB2PROJ.MA_99_RCUU_ANALYSIS_V3 WHERE RCUU_TAG = 'N' AND INBASE_TAG = 'Y' AND VLR_TAG = 'Y'; 

DROP TABLE DB2PROJ.MA_RCUU_NONRC_PCN_TEMP ;
CREATE TABLE DB2PROJ.MA_RCUU_NONRC_PCN_TEMP AS (
SELECT A.SUBS_CIRCLE_ID, A.SUBS_MSISDN,
CASE WHEN B.SUBS_MSISDN IS NOT NULL THEN 'Y' ELSE 'N' END AS RCUU_TAG,
CASE WHEN VLR.SUBS_MSISDN IS NOT NULL THEN 'Y' ELSE 'N' END AS VLR_TAG,
CASE WHEN DND.SUBS_MSISDN IS NOT NULL THEN 'Y' ELSE 'N' END AS DND_TAG
 FROM 
(SELECT SUBS_CIRCLE_ID, SUBS_MSISDN FROM DB2PROJ.MA_99_RCUU_ANALYSIS_V3 WHERE RCUU_TAG = 'N') A  ---RCUU TAG 30OCT2023

LEFT JOIN (
SELECT RECH.SUBS_CIRCLE_ID,RECH.SUBS_MSISDN,SUBS.UNBAR_DATE
,CASE WHEN SUBS.UNBAR_DATE BETWEEN '2023-11-01' AND CURRENT DATE -2 THEN 'FR' ELSE 'BASE' END SLAB 
,CASE WHEN RECH.MX IN (219,499,539,2899,155,195,239,329,459,479,1449,199,269,699,1799,209,327,149,179,249,599,839,901,109,379,299,319,359,719,475,409,1066,666,399,2595,1499,129,537,601,3099,2399,398,337,449,501,795,1197,119,509,558,401,999,1699,405,169,296,701,595,289,801) THEN 'UL' 
ELSE 'NUL'  END TSLAB
FROM (SELECT X.SUBS_MSISDN,X.SUBS_CIRCLE_ID,MAX(X.RCHG_MRP_AMT ) MX 
FROM (SELECT DISTINCT SUBS_MSISDN ,RCHG_MRP_AMT,SUBS_CIRCLE_ID FROM DIM_DATALAKE.DIM_SUBS_RCHG_DFRMNT_BASE
WHERE REVENUE_START_DT<=CURRENT DATE -2 AND REVENUE_END_DT>=CURRENT DATE -2
AND SUBS_CIRCLE_ID IN (21,22)
AND (RCHG_CATEGORY=16)
UNION
SELECT DISTINCT SUBS_MSISDN ,RCHG_MRP_AMT,SUBS_CIRCLE_ID 
FROM DIM_DATALAKE.DIM_SUBS_RCHG_DFRMNT_BASE_JAN_FEB_STATIC
WHERE REVENUE_START_DT<=CURRENT DATE -2 AND REVENUE_END_DT>=CURRENT DATE -2 AND SUBS_CIRCLE_ID IN (21,22) AND (RCHG_CATEGORY=16)

UNION

SELECT SUBS_MSISDN,MAX(RCHG_MRP_AMT) RCHG_MRP_AMT,SUBS_CIRCLE_ID 
FROM FACT_DATALAKE.FCT_SUBS_RCHG_HISTORY 
WHERE RCHG_DT BETWEEN DATE(CURRENT DATE -2)-29 DAYS AND CURRENT DATE -2 
AND SUBS_CIRCLE_ID IN (21,22) 
AND RCHG_MRP_AMT>0 
GROUP BY SUBS_MSISDN,SUBS_CIRCLE_ID)X
GROUP  BY X.SUBS_MSISDN,X.SUBS_CIRCLE_ID)RECH ,
(SELECT DISTINCT SUBS_MSISDN FROM AGGR_DATALAKE.AGGR_USAGE_CUSTOMERS
WHERE SUBS_CIRCLE_ID IN (21,22)
AND RES_FLAG_90 = 'Y' 
AND REPORT_DATE=CURRENT DATE -2 
)RES,
(SELECT DISTINCT SUBS_MSISDN ,UNBAR_DATE FROM DIM_DATALAKE.DIM_SUBS_MASTER 
WHERE CIRCLE_ID IN (21,22)
AND DISCONNECTION_DATE >CURRENT DATE -2 
) SUBS
WHERE RECH.SUBS_MSISDN=SUBS.SUBS_MSISDN                            
AND RECH.SUBS_MSISDN=RES.SUBS_MSISDN) B

 ON A.SUBS_MSISDN = B.SUBS_MSISDN

LEFT JOIN (SELECT DISTINCT SUBS_MSISDN FROM FACT_DATALAKE.FCT_SUBS_VLR_HISTORY WHERE SUBS_CIRCLE_ID IN (21,22) AND VLR_START_DATE <= CURRENT DATE - 2 DAYS AND VLR_END_DATE >CURRENT DATE - 2 DAYS)VLR 
    ON A.SUBS_MSISDN = VLR.SUBS_MSISDN

LEFT JOIN (SELECT SUBS_MSISDN FROM FACT_DATALAKE.FCT_SUBS_DLT_PREF_HISTORY WHERE DND_PRF_END_DT='9999-12-31' GROUP BY SUBS_MSISDN)DND
    ON A.SUBS_MSISDN = DND.SUBS_MSISDN

INNER JOIN (SELECT SUBS_MSISDN,BRAND_ID FROM DIM_DATALAKE.DIM_SUBS_MASTER WHERE DISCONNECTION_DATE >= (CURRENT DATE - 2) AND UNBAR_DATE <= (CURRENT DATE - 2)AND CIRCLE_ID IN (21,22) AND BRAND_ID IN ('1','2')) IN -- USE LATEST TABLE
	 ON A.SUBS_MSISDN = IN.SUBS_MSISDN
)WITH NO DATA ;


INSERT INTO DB2PROJ.MA_RCUU_NONRC_PCN_TEMP  (
SELECT A.SUBS_CIRCLE_ID, A.SUBS_MSISDN,
CASE WHEN B.SUBS_MSISDN IS NOT NULL THEN 'Y' ELSE 'N' END AS RCUU_TAG,
CASE WHEN VLR.SUBS_MSISDN IS NOT NULL THEN 'Y' ELSE 'N' END AS VLR_TAG,
CASE WHEN DND.SUBS_MSISDN IS NOT NULL THEN 'Y' ELSE 'N' END AS DND_TAG
 FROM 
(SELECT SUBS_CIRCLE_ID, SUBS_MSISDN FROM DB2PROJ.MA_99_RCUU_ANALYSIS_V3 WHERE RCUU_TAG = 'N') A  ---RCUU TAG 30OCT2023

LEFT JOIN (
SELECT RECH.SUBS_CIRCLE_ID,RECH.SUBS_MSISDN,SUBS.UNBAR_DATE
,CASE WHEN SUBS.UNBAR_DATE BETWEEN '2023-11-01' AND CURRENT DATE -2 THEN 'FR' ELSE 'BASE' END SLAB 
,CASE WHEN RECH.MX IN (219,499,539,2899,155,195,239,329,459,479,1449,199,269,699,1799,209,327,149,179,249,599,839,901,109,379,299,319,359,719,475,409,1066,666,399,2595,1499,129,537,601,3099,2399,398,337,449,501,795,1197,119,509,558,401,999,1699,405,169,296,701,595,289,801) THEN 'UL' 
ELSE 'NUL'  END TSLAB
FROM (SELECT X.SUBS_MSISDN,X.SUBS_CIRCLE_ID,MAX(X.RCHG_MRP_AMT ) MX 
FROM (SELECT DISTINCT SUBS_MSISDN ,RCHG_MRP_AMT,SUBS_CIRCLE_ID FROM DIM_DATALAKE.DIM_SUBS_RCHG_DFRMNT_BASE
WHERE REVENUE_START_DT<=CURRENT DATE -2 AND REVENUE_END_DT>=CURRENT DATE -2
AND SUBS_CIRCLE_ID IN (21,22)
AND (RCHG_CATEGORY=16)
UNION
SELECT DISTINCT SUBS_MSISDN ,RCHG_MRP_AMT,SUBS_CIRCLE_ID 
FROM DIM_DATALAKE.DIM_SUBS_RCHG_DFRMNT_BASE_JAN_FEB_STATIC
WHERE REVENUE_START_DT<=CURRENT DATE -2 AND REVENUE_END_DT>=CURRENT DATE -2 AND SUBS_CIRCLE_ID IN (21,22) AND (RCHG_CATEGORY=16)

UNION

SELECT SUBS_MSISDN,MAX(RCHG_MRP_AMT) RCHG_MRP_AMT,SUBS_CIRCLE_ID 
FROM FACT_DATALAKE.FCT_SUBS_RCHG_HISTORY 
WHERE RCHG_DT BETWEEN DATE(CURRENT DATE -2)-29 DAYS AND CURRENT DATE -2 
AND SUBS_CIRCLE_ID IN (21,22) 
AND RCHG_MRP_AMT>0 
GROUP BY SUBS_MSISDN,SUBS_CIRCLE_ID)X
GROUP  BY X.SUBS_MSISDN,X.SUBS_CIRCLE_ID)RECH ,
(SELECT DISTINCT SUBS_MSISDN FROM AGGR_DATALAKE.AGGR_USAGE_CUSTOMERS
WHERE SUBS_CIRCLE_ID IN (21,22)
AND RES_FLAG_90 = 'Y' 
AND REPORT_DATE=CURRENT DATE -2 
)RES,
(SELECT DISTINCT SUBS_MSISDN ,UNBAR_DATE FROM DIM_DATALAKE.DIM_SUBS_MASTER 
WHERE CIRCLE_ID IN (21,22)
AND DISCONNECTION_DATE >CURRENT DATE -2 
) SUBS
WHERE RECH.SUBS_MSISDN=SUBS.SUBS_MSISDN                            
AND RECH.SUBS_MSISDN=RES.SUBS_MSISDN) B

 ON A.SUBS_MSISDN = B.SUBS_MSISDN

LEFT JOIN (SELECT DISTINCT SUBS_MSISDN FROM FACT_DATALAKE.FCT_SUBS_VLR_HISTORY WHERE SUBS_CIRCLE_ID IN (21,22) AND VLR_START_DATE <= CURRENT DATE - 2 DAYS AND VLR_END_DATE >CURRENT DATE - 2 DAYS)VLR 
    ON A.SUBS_MSISDN = VLR.SUBS_MSISDN

LEFT JOIN (SELECT SUBS_MSISDN FROM FACT_DATALAKE.FCT_SUBS_DLT_PREF_HISTORY WHERE DND_PRF_END_DT='9999-12-31' GROUP BY SUBS_MSISDN)DND
    ON A.SUBS_MSISDN = DND.SUBS_MSISDN

INNER JOIN (SELECT SUBS_MSISDN,BRAND_ID FROM DIM_DATALAKE.DIM_SUBS_MASTER WHERE DISCONNECTION_DATE >= (CURRENT DATE - 2) AND UNBAR_DATE <= (CURRENT DATE - 2)AND CIRCLE_ID IN (21,22) AND BRAND_ID IN ('1','2')) IN -- USE LATEST TABLE
	 ON A.SUBS_MSISDN = IN.SUBS_MSISDN) ;
	 
grant select on DB2PROJ.MA_RCUU_NONRC_PCN_TEMP to public ;