-----CUTS
-------VLR 'Y', DND 'N',IN 'Y' ,PRE,POST


---479,539,719,839-----

DROP TABLE DB2PROJ.Hari_479_719_Base;

CREATE TABLE DB2PROJ.Hari_479_719_Base AS ( 
SELECT A.SUBS_MSISDN,A.REVENUE_END_DT,A.SUBS_CIRCLE_ID,A.RCHG_MRP_AMT
,CASE WHEN VLR.SUBS_MSISDN IS NOT NULL THEN 'Y' ELSE 'N' END AS VLR_TAG
,CASE WHEN DND.SUBS_MSISDN IS NOT NULL THEN 'Y' ELSE 'N' END AS DND_TAG
,CASE WHEN HS.DEVICE_TYPE IN('4G','5G')  THEN '4G' ELSE 'NON4G' END AS DEVICE_TYPE

FROM 
 (SELECT SUBS_MSISDN,REVENUE_END_DT,SUBS_CIRCLE_ID,RCHG_MRP_AMT,REPORTED_DATE,RN FROM 
(SELECT SUBS_MSISDN,REVENUE_END_DT,SUBS_CIRCLE_ID,RCHG_MRP_AMT,REPORTED_DATE,
ROW_NUMBER() OVER (PARTITION BY SUBS_MSISDN ORDER BY SUBS_MSISDN,REVENUE_END_DT desc)RN FROM DIM_DATALAKE.DIM_SUBS_RCHG_DFRMNT_BASE
WHERE SUBS_CIRCLE_ID IN (21,22) AND RCHG_CATEGORY IN (11,16) AND RCHG_MRP_AMT > 0 )
WHERE RN = 1) A

--INNER JOIN 
--(SELECT * FROM DB2PROJ.HS_TEMP_USAGE WHERE DATA_USAGE_MB>=1024*30)B 
--ON A.SUBS_MSISDN=B.SUBS_MSISDN 
--WHERE A.RN = 1 )X     -----------BASE
LEFT JOIN (SELECT RIGHT(SUBS_MSISDN,10) AS SUBS_MSISDN,DEVICE_TYPE FROM  DB2PROJ.HANDSET_MTD_TUP) HS 
                 ON A.SUBS_MSISDN = HS.SUBS_MSISDN

LEFT JOIN 
(SELECT DISTINCT SUBS_MSISDN FROM fact_DATALAKE.FCT_SUBS_VLR_HISTORY WHERE SUBS_CIRCLE_ID IN (21,22) AND VLR_START_DATE <= CURRENT DATE - 2 DAYS AND VLR_END_DATE >CURRENT DATE - 2 DAYS)VLR 
    ON A.SUBS_MSISDN = VLR.SUBS_MSISDN
LEFT JOIN 
(Select subs_msisdn from fact_datalake.FCT_SUBS_DLT_PREF_HISTORY WHERE dnd_prf_end_dt='9999-12-31' GROUP BY subs_msisdn)DND
    ON A.SUBS_MSISDN = DND.SUBS_MSISDN
 WHERE  A.SUBS_MSISDN IN (SELECT SUBS_MSISDN FROM DIM_DATALAKE.DIM_SUBS_MASTER WHERE DISCONNECTION_DATE >= (CURRENT DATE - 2) AND UNBAR_DATE <= (CURRENT DATE - 2)AND CIRCLE_ID IN (21,22) AND BRAND_ID IN ('1','2') GROUP BY SUBS_MSISDN)
AND A.RCHG_MRP_AMT IN ('479','539','719','839') AND A.REVENUE_END_DT BETWEEN CURRENT DATE -7 AND CURRENT DATE +3 ) WITH NO DATA ;

INSERT INTO DB2PROJ.Hari_479_719_Base ( 
SELECT A.SUBS_MSISDN,A.REVENUE_END_DT,A.SUBS_CIRCLE_ID,A.RCHG_MRP_AMT
,CASE WHEN VLR.SUBS_MSISDN IS NOT NULL THEN 'Y' ELSE 'N' END AS VLR_TAG
,CASE WHEN DND.SUBS_MSISDN IS NOT NULL THEN 'Y' ELSE 'N' END AS DND_TAG
,CASE WHEN HS.DEVICE_TYPE IN('4G','5G')  THEN '4G' ELSE 'NON4G' END AS DEVICE_TYPE

FROM 
 (SELECT SUBS_MSISDN,REVENUE_END_DT,SUBS_CIRCLE_ID,RCHG_MRP_AMT,REPORTED_DATE,RN FROM 
(SELECT SUBS_MSISDN,REVENUE_END_DT,SUBS_CIRCLE_ID,RCHG_MRP_AMT,REPORTED_DATE,
ROW_NUMBER() OVER (PARTITION BY SUBS_MSISDN ORDER BY SUBS_MSISDN,REVENUE_END_DT desc)RN FROM DIM_DATALAKE.DIM_SUBS_RCHG_DFRMNT_BASE
WHERE SUBS_CIRCLE_ID IN (21,22) AND RCHG_CATEGORY IN (11,16) AND RCHG_MRP_AMT > 0 )
WHERE RN = 1) A

--INNER JOIN 
--(SELECT * FROM DB2PROJ.HS_TEMP_USAGE WHERE DATA_USAGE_MB>=1024*30)B 
--ON A.SUBS_MSISDN=B.SUBS_MSISDN 
--WHERE A.RN = 1 )X     -----------BASE
LEFT JOIN (SELECT RIGHT(SUBS_MSISDN,10) AS SUBS_MSISDN,DEVICE_TYPE FROM  DB2PROJ.HANDSET_MTD_TUP) HS 
                 ON A.SUBS_MSISDN = HS.SUBS_MSISDN

LEFT JOIN 
(SELECT DISTINCT SUBS_MSISDN FROM fact_DATALAKE.FCT_SUBS_VLR_HISTORY WHERE SUBS_CIRCLE_ID IN (21,22) AND VLR_START_DATE <= CURRENT DATE - 2 DAYS AND VLR_END_DATE >CURRENT DATE - 2 DAYS)VLR 
    ON A.SUBS_MSISDN = VLR.SUBS_MSISDN
LEFT JOIN 
(Select subs_msisdn from fact_datalake.FCT_SUBS_DLT_PREF_HISTORY WHERE dnd_prf_end_dt='9999-12-31' GROUP BY subs_msisdn)DND
    ON A.SUBS_MSISDN = DND.SUBS_MSISDN
 WHERE  A.SUBS_MSISDN IN (SELECT SUBS_MSISDN FROM DIM_DATALAKE.DIM_SUBS_MASTER WHERE DISCONNECTION_DATE >= (CURRENT DATE - 2) AND UNBAR_DATE <= (CURRENT DATE - 2)AND CIRCLE_ID IN (21,22) AND BRAND_ID IN ('1','2') GROUP BY SUBS_MSISDN)
AND A.RCHG_MRP_AMT IN ('479','539','719','839') AND A.REVENUE_END_DT BETWEEN CURRENT DATE -7 AND CURRENT DATE +3 );